### ISSUE TITLE
Bugs with certain searches

### ISSUE THREAD

**Issue by gabriellafquattrone** [deanmccluskey/Project-1#33]
Alan Wong: returns 

> The cuisine of Hawaii incorporates five distinct styles of food reflecting the diverse food history of settlement and immigration in the Hawaiian Islands. In the pre

The text is cut off. Need to figure out why

Ugandan Knuckles: returns

<img width="570" alt="Screen Shot 2019-11-05 at 9 50 53 AM" src="https://user-images.githubusercontent.com/30669574/68232362-ccb1a800-ffb1-11e9-88f6-7376452834f7.png">
 
An empty box.

1000 J Street: doesn't return our query error.

Please add and remove from this list as you find more bugs and resolve bugs.

**Comment by Jballking** [comment]
issue resolved after working with TA
